# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

defaultContentLanguage: en

languages:
  en:
    languageCode: en-us
    languageName: English
    params:
      locale: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  # contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
#  zh:
#    languageCode: zh-Hans
#    languageName: Chinese
#    contentDir: content/zh
#    title: Chinese website title...
#    params:
#      locale: zh-Hans
#      description: Site description in Chinese...
#    menu:
#      main:
#        - name: 传
#          url: '#about'
#          weight: 1
